- .codespellrc
- .taplo.toml
Adds `.codespellrc` and `.taplo.toml` configs.
> chore: add codespell/taplo configs

- .github/workflows/docs.yml
- .github/workflows/lint.yml
- .github/workflows/unit.yml
- buf.yaml
Add protobuf linter into lint workflow.
Merge after other pending PR's.
Merge after #1 #2 
Closes #5
> chore: protobuf lint

- crates/p2p/src/swarm/mod.rs
- crates/p2p/tests/common.rs
This is needed for P2P users to specify `memory` or `tcp` transport and whether the database should be temporary or not, for tests and production accordingly.
> Make swarm and database constructable from outside of P2P type

- Cargo.toml
- crates/db/Cargo.toml
- crates/p2p/Cargo.toml
Move some dependencies from `[dev-dependencies]` into `[workspace.dependencies]`
> refactor: Reuse workspace deps in dev-deps

- crates/p2p/src/swarm/mod.rs
- crates/p2p/tests/gossipsub.rs
`init` was renamed to `establish_connections` and made public, so stages of P2P readiness can be controlled by the crate user.
Added test with sequential handling of multiple scopes with multiple operators.
> feat: Add new methods for tests, make `init` public and add test

- Cargo.lock
- Cargo.toml
- crates/db/Cargo.toml
- crates/db/src/lib.rs
- crates/db/src/sled.rs
- crates/p2p/Cargo.toml
- crates/p2p/src/swarm/mod.rs
- crates/p2p/tests/common.rs
- crates/p2p/tests/gossipsub.rs
Migrate from using `snafu` crate to using `thiserror` crate for handling errors.
Resolves https://github.com/alpenlabs/strata-p2p/pull/4#discussion_r1913788499
> refactor: migrated from snafu to thiserror

- crates/db/src/sled.rs
- crates/p2p/src/events.rs
- crates/p2p/src/swarm/mod.rs
- crates/p2p/tests/common.rs
- crates/p2p/tests/gossipsub.rs
Update request message command to request from neighbouring peers if distributor is unavailable.
> refactor: request command use fallback neighbours request

- Cargo.toml
- crates/db/Cargo.toml
- crates/db/src/lib.rs
- crates/db/src/prost_serde.rs
- crates/db/src/sled.rs
- crates/p2p/src/commands.rs
- crates/p2p/src/events.rs
- crates/p2p/src/lib.rs
- crates/p2p/src/swarm/behavior.rs
- crates/p2p/src/swarm/codec.rs
- crates/p2p/src/swarm/errors.rs
- crates/p2p/src/swarm/handle.rs
- crates/p2p/src/swarm/mod.rs
- crates/p2p/tests/common.rs
- crates/p2p/tests/gossipsub.rs
- crates/types/src/lib.rs
- crates/types/src/operator.rs
- crates/types/src/scope.rs
- crates/types/src/sessionid.rs
- crates/wire/build.rs
- crates/wire/src/lib.rs
- crates/wire/src/p2p/mod.rs
- crates/wire/src/p2p/v1.rs
- crates/wire/src/p2p/v1/typed.rs
- proto/strata/bitvm2/p2p/v1/getmessage.proto
- proto/strata/bitvm2/p2p/v1/gossipsub.proto
> Documentation updates

- crates/p2p/src/lib.rs
- crates/types/src/lib.rs
- crates/types/src/stake_data.rs
- crates/types/src/wots.rs
- crates/wire/src/lib.rs
- crates/wire/src/p2p/v1/typed.rs
- rust-toolchain.toml
Needed for https://github.com/alpenlabs/strata-bridge/pull/46
This is annoying :/
> chore: revert to nightly 2024-11-01

- .github/workflows/dependencies.yml
- .github/workflows/docs.yml
- .github/workflows/lint.yml
- .github/workflows/unit.yml
It will automatically get from `rust-toolchain.toml`
> ci: remove hardcoded nightly

- crates/p2p/src/swarm/handle.rs
Implements `Clone` for `P2PHandle`.
> feat: manual `Clone` for `P2PHandle`

- crates/types/src/scope.rs
- crates/types/src/session_id.rs
This PR retains the compile-time known lengths of Scope and SessionId in their respective AsRef implementations. We can "forget" the length thereafter by re-slicing with `[..]`
> fix AsRef implementation ergonomics for Scope and SessionId

- Cargo.lock
- crates/types/Cargo.toml
- crates/types/src/operator.rs
This PR serializes the `P2POperatorPubKey` type to hex-encoded string for conveniently using it in config files.
> feat(types): serialize `P2POperatorPubKey` as hex for convenience

- crates/p2p/src/commands.rs
- crates/p2p/src/tests/common.rs
- crates/wire/src/p2p/v1/typed.rs
- proto/strata/bitvm2/p2p/v1/getmessage.proto
- proto/strata/bitvm2/p2p/v1/gossipsub.proto
Adds an `index` field to the `DepositSetup` gossip (get request) messages.
> feat!: add index to deposit setup

- Cargo.lock
ID:        RUSTSEC-2025-0024
URL:       https://rustsec.org/advisories/RUSTSEC-2025-0024
Closes: https://github.com/alpenlabs/strata-p2p/security/dependabot/5
Closes: https://github.com/alpenlabs/strata-p2p/security/dependabot/5
> chore(deps): bump crossbeam-channel and tokio

- .github/workflows/cron-nightly-rust.yml
- .github/workflows/cron-zizmor.yml
- .github/workflows/dependencies.yml
- .github/workflows/docs.yml
- .github/workflows/lint-actions.yml
- .github/workflows/lint.yml
- .github/workflows/security.yml
- .github/workflows/unit.yml
- .github/workflows/zizmor.yml
- zizmor.yml
This PR adds a hash-pin to all external workflows as per the requirement in zizmor's default security policy as of version 1.60. This also updates the version of sccache.
> fix(ci): hash-pin all external workflows and update sccache

- crates/p2p/src/swarm/mod.rs
- crates/p2p/src/tests/common.rs
This PR adds a retry mechanism when connecting to the swarm and subscribing to topics. It does so by adding a max retry count parameter and additional logs to help debug issues in the consumer.
> feat(swarm): add retry mechanism for initial connection attempt

- crates/p2p/src/swarm/mod.rs
Moving stuff away from info! and debug! into trace!, and from error! into warn!
> fix: less verbose logging

- Cargo.lock
- crates/p2p/Cargo.toml
- crates/p2p/src/commands.rs
- crates/p2p/src/swarm/mod.rs
- crates/p2p/src/tests/common.rs
- crates/p2p/src/tests/gossipsub.rs
- crates/p2p/src/tests/is_connected.rs
- crates/p2p/src/tests/mod.rs
- crates/p2p/src/tests/new_op.rs
- crates/p2p/src/tests/request_response.rs
Absence of really working tests.
Low code coverage
The work on tests began to understand if it's possible to write fake ed25519 keypair (with valid only public key), but after further investigation it seems impossible to do in any good way. Though, here's just some basic tests that increase code coverage from 30-smth % to 58.7% ( according to `cargo tarpaunlin --tests --engine llvm` )
> Add some tests

- Cargo.lock
- Cargo.toml
- crates/p2p/Cargo.toml
- crates/p2p/src/commands.rs
- crates/p2p/src/events.rs
- crates/p2p/src/swarm/behavior.rs
- crates/p2p/src/swarm/dial_manager.rs
- crates/p2p/src/swarm/handle.rs
- crates/p2p/src/swarm/mod.rs
- crates/p2p/src/tests/common.rs
- crates/p2p/src/tests/gossipsub.rs
- crates/p2p/src/tests/is_connected.rs
- crates/p2p/src/tests/mod.rs
- crates/p2p/src/tests/new_op.rs
- crates/p2p/src/tests/quic.rs
- crates/p2p/src/tests/request_response.rs
- crates/p2p/src/tests/setup_invalid_signature.rs
Main changes: 
1. Add support for the QUIC protocol, enabled via the `quic` feature, and include a test to validate this functionality.
2. Update the `ConnectToPeer` command to accept a list of multiaddresses; this command now prioritizes connecting to QUIC addresses first, then falls back to TCP addresses.
3. Introduce a new `ConnectToAddress` command to allow connecting to a multiaddress without requiring a known `peer_id`.
> Quic protocol

- Cargo.lock
- Cargo.toml
- crates/p2p/Cargo.toml
- crates/p2p/src/swarm/errors.rs
- crates/p2p/src/swarm/message/serde.rs
- crates/p2p/src/swarm/message/signed.rs
- crates/p2p/src/swarm/mod.rs
- crates/p2p/src/swarm/setup/flexbuffers_codec.rs
- crates/p2p/src/swarm/setup/mod.rs
- crates/p2p/src/swarm/setup/upgrade.rs
- crates/p2p/src/tests/flexbuffers.rs
- crates/p2p/src/tests/flexbuffers_serialization.rs
- crates/p2p/src/tests/mod.rs
Add Flexbuffers serialization/deserialization
> Serde with flexbuffers

- crates/p2p/src/swarm/mod.rs
- crates/p2p/src/swarm/setup/behavior.rs
- crates/p2p/src/swarm/setup/events.rs
- crates/p2p/src/swarm/setup/handler.rs
Just forwarded up `NegotiationFailed` to `crates/p2p/src/swarm/mod.rs` and disconnect remote peer in this case. Also fixed some documentation strings in events.rs for Setup.
> byos: Fixed ignoring of Setup negotiation failing.
